name: EithonInsanityRun
main: net.eithon.plugin.insanityrun.Plugin
version: 1.2
author: vanbrayne
description: A Minecraft plugin for insanity run mini game
depend: [EithonLibrary]
commands:
  eir:
    description: Control jump pads
    usage: /eir add | link | remove  | goto | list | join_named_arena | leave | reset | price | reward
    permission-message: You don't have <permission>
permissions:
  eir.*:
    description: Gives access to all eir commands
    default: op
    eir.add: true
    eir.link: true
    eir.remove: true
    eir.list: true
    eir.goto: true
    eir.join: true
    eir.leave: true
    eir.reset: true
    eir.price: true
    eir.reward: true
  eir.add:
    description: Access to /eir add command
    default: op
  eir.link:
    description: Access to /eir link command
    default: op
  eir.remove:
    description: Access to /eir remove command
    default: op
  eir.list:
    description: Access to /eir list command
    default: op
  eir.goto:
    description: Access to /eir goto command
    default: op
  eir.join:
    description: Access to /eir join command
    default: op
  eir.leave:
    description: Access to /eir leave command
    default: op
  eir.reset:
    description: Access to /eir reset command
    default: op
  eir.price:
    description: Access to /eir price command
    default: op
  eir.reward:
    description: Access to /eir reward command
    default: op
